#!/usr/bin/env node
// Copyright (c) 2025 Amrutha Kollu. All rights reserved.
// Licensed under the Functional Source License, Version 1.1 (FSL-1.1-MIT) — see LICENSE for details.

/**
 * fixel verify — drift detection between Figma and component source
 *
 * Reads a component's .fixel.json spec (generated by fixel generate) and
 * checks that the current source file still matches the Figma values recorded
 * at generation time.  When run with --node, re-fetches live Figma data
 * instead of using the stored spec.
 *
 * Usage:
 *   fixel verify --component Badge
 *   fixel verify --component Badge --node FILEKEY:NODEID   (live Figma)
 *   fixel verify                                           (all components)
 *   fixel verify --write-overrides                         (register intentional deviations)
 *
 * Flags:
 *   --component <Name>    Check one component (default: all with spec files)
 *   --node <FILEKEY:ID>   Re-fetch live Figma data (requires FIGMA_ACCESS_TOKEN)
 *   --no-cache            Bypass the Figma API cache (implies live fetch)
 *   --write-overrides     After reporting drift, prompt to register intentional
 *                         deviations in fixel.overrides.json.  On future runs
 *                         those checks print ⊘ OVERRIDE instead of ✗ DRIFT.
 *
 * Exit codes:
 *   0  all components pass (overrides and warnings are acceptable)
 *   1  one or more components have unregistered drift errors
 *   2  no spec files found — run fixel generate first
 */

import * as fs   from 'node:fs';
import * as path from 'node:path';

import {
  FixelConfigError,
  loadConfig,
  loadEnvFile,
  parseNodeArg,
  resolveFigmaToken,
} from '../core/config';

import {
  FigmaApiError,
  fetchFigmaNode,
  findComponentRoot,
} from '../core/figma-client';

import {
  extractTextStyles,
} from '../core/typography';

import {
  extractSpacingEntries,
  extractIconSizes,
  extractCornerRadii,
  type FixelSpec,
} from '../core/extractors';

import {
  loadOverrides,
  saveOverrides,
  setOverride,
} from '../core/overrides';

import {
  type CheckStatus,
  type CheckResult,
  runDriftChecks,
  componentStatus,
} from '../core/drift';

// ─── ANSI helpers ─────────────────────────────────────────────────────────────

const C = {
  reset:  '\x1b[0m',
  bold:   '\x1b[1m',
  dim:    '\x1b[2m',
  green:  '\x1b[32m',
  yellow: '\x1b[33m',
  red:    '\x1b[31m',
  cyan:   '\x1b[36m',
};

// ─── CLI args ─────────────────────────────────────────────────────────────────

function normalizeNodeArg(nodeArg: string): string {
  const colonIndex = nodeArg.indexOf(':');
  if (colonIndex === -1) return nodeArg;
  const fileKey = nodeArg.substring(0, colonIndex);
  const nodeId  = nodeArg.substring(colonIndex + 1).replace(/-/g, ':');
  return `${fileKey}:${nodeId}`;
}

interface VerifyArgs {
  component:      string | null;
  nodeRaw:        string | null;
  noCache:        boolean;
  writeOverrides: boolean;
}

function parseArgs(argv: string[]): VerifyArgs {
  const flag = (f: string): string | null => {
    const i = argv.indexOf(f);
    return i !== -1 ? (argv[i + 1] ?? null) : null;
  };
  const nodeRaw = flag('--node');
  return {
    component:      flag('--component'),
    nodeRaw:        nodeRaw ? normalizeNodeArg(nodeRaw) : null,
    noCache:        argv.includes('--no-cache'),
    writeOverrides: argv.includes('--write-overrides'),
  };
}

// ─── Types ────────────────────────────────────────────────────────────────────

interface ComponentReport {
  name:        string;
  specPath:    string | null;
  codePath:    string;
  figmaNode:   string;
  generatedAt: string;
  checks:      CheckResult[];
  status:      CheckStatus;
}

// ─── Spec discovery ───────────────────────────────────────────────────────────

interface SpecEntry {
  name:     string;
  specPath: string | null;
  codePath: string;
}

function findComponents(
  componentDir:    string,
  componentFilter: string | null,
  requireSpec:     boolean,
): SpecEntry[] {
  if (!fs.existsSync(componentDir)) return [];
  const entries: SpecEntry[] = [];

  for (const name of fs.readdirSync(componentDir)) {
    if (componentFilter && name !== componentFilter) continue;
    const dir      = path.join(componentDir, name);
    if (!fs.statSync(dir).isDirectory()) continue;
    const specPath = path.join(dir, `${name}.fixel.json`);
    const codePath = path.join(dir, `${name}.tsx`);
    const hasSpec  = fs.existsSync(specPath);
    if (!fs.existsSync(codePath)) continue;
    if (requireSpec && !hasSpec)  continue;
    entries.push({ name, specPath: hasSpec ? specPath : null, codePath });
  }

  return entries.sort((a, b) => a.name.localeCompare(b.name));
}

// ─── Report printer ───────────────────────────────────────────────────────────

function coloured(status: CheckStatus, text: string): string {
  if (status === 'pass')     return `${C.green}${text}${C.reset}`;
  if (status === 'warn')     return `${C.yellow}${text}${C.reset}`;
  if (status === 'override') return `${C.cyan}${text}${C.reset}`;
  return `${C.red}${text}${C.reset}`;
}

function daysSince(iso: string): number {
  return Math.floor((Date.now() - new Date(iso).getTime()) / 86_400_000);
}

function printComponentReport(report: ComponentReport, isLive: boolean): void {
  const age      = daysSince(report.generatedAt);
  const ageLabel = age === 0 ? 'today' : age === 1 ? '1 day ago' : `${age} days ago`;
  const src      = isLive ? 'live Figma' : 'stored spec';

  console.log(
    `\n${C.bold}  ${report.name}${C.reset}` +
    `  ${C.dim}(node ${report.figmaNode} · generated ${ageLabel} · ${src})${C.reset}`,
  );
  console.log(`  ${'─'.repeat(60)}`);

  for (const c of report.checks) {
    const icon =
      c.status === 'pass'     ? '✓' :
      c.status === 'warn'     ? '⚠' :
      c.status === 'override' ? '⊘' : '✗';
    console.log(
      `    ${coloured(c.status, icon)}  ${C.dim}${c.label}${C.reset}  ${c.detail}`,
    );
  }

  const errors    = report.checks.filter((c) => c.status === 'fail').length;
  const warnings  = report.checks.filter((c) => c.status === 'warn').length;
  const passes    = report.checks.filter((c) => c.status === 'pass').length;
  const overrides = report.checks.filter((c) => c.status === 'override').length;

  const statusText = report.status === 'pass'
    ? `${C.green}${C.bold}PASS${C.reset}`
    : report.status === 'warn'
      ? `${C.yellow}${C.bold}PASS (with warnings)${C.reset}`
      : `${C.red}${C.bold}FAIL${C.reset}`;

  const overrideNote = overrides > 0
    ? `  ${C.cyan}${overrides} override(s)${C.reset}`
    : '';

  console.log(
    `\n    ${statusText}  ` +
    `${C.dim}${passes} passed · ${warnings} warnings · ${errors} errors${C.reset}` +
    overrideNote,
  );
}

// ─── Main ─────────────────────────────────────────────────────────────────────

async function main(): Promise<void> {
  const args = parseArgs(process.argv.slice(2));

  // Require --component when --node is used: applying one node's live Figma
  // data to every component in the directory would produce silently wrong results.
  if (args.nodeRaw && !args.component) {
    console.error(
      `\n  ${C.red}✗${C.reset}  --node requires --component.\n\n` +
      `  Passing --node without --component would apply one Figma node's data\n` +
      `  to every component in the directory — almost certainly wrong.\n\n` +
      `  Usage:\n` +
      `    fixel verify --component Badge --node FILEKEY:NODEID\n\n` +
      `  To check all components offline against their stored specs:\n` +
      `    fixel verify\n`,
    );
    process.exit(1);
  }

  loadEnvFile();
  const config    = loadConfig();
  const overrides = loadOverrides(process.cwd());

  const componentBaseDir = path.resolve(process.cwd(), config.output.componentDir);
  const isLive    = !!args.nodeRaw;
  const needsSpec = !isLive;

  const entries = findComponents(componentBaseDir, args.component, needsSpec);

  if (entries.length === 0) {
    if (args.component) {
      const codePath = path.join(componentBaseDir, args.component, `${args.component}.tsx`);
      if (!fs.existsSync(codePath)) {
        console.error(
          `\n  ${C.red}✗${C.reset}  Component "${args.component}" not found.\n` +
          `     Expected: ${codePath}\n`,
        );
      } else {
        console.error(
          `\n  ${C.yellow}⚠${C.reset}  "${args.component}" has no fixel.json spec yet.\n\n` +
          `  Verify against live Figma:\n` +
          `    ${C.cyan}fixel verify --component ${args.component} --node FILEKEY:NODEID${C.reset}\n\n` +
          `  Or regenerate the component to create a spec:\n` +
          `    ${C.cyan}fixel generate --name ${args.component} --node FILEKEY:NODEID --force${C.reset}\n`,
        );
      }
    } else {
      console.error(
        `\n  ${C.yellow}⚠${C.reset}  No fixel.json spec files found under ${config.output.componentDir}.\n` +
        `     Run "fixel generate" first to create spec files.\n`,
      );
    }
    process.exit(2);
  }

  const modeLabel = isLive
    ? `${C.cyan}live Figma${C.reset}`
    : `${C.dim}stored spec${C.reset}`;

  console.log(
    `\n${C.bold}  fixel verify${C.reset}  ` +
    `${entries.length} component(s)  ·  ${modeLabel}`,
  );

  const reports: ComponentReport[] = [];

  if (isLive) {
    // ── Live mode: re-fetch from Figma and re-run resolvers ──────────────────
    const parsed = parseNodeArg(args.nodeRaw!);

    const fetches = await Promise.allSettled(
      entries.map(async (entry) => {
        const rawNode = await fetchFigmaNode({
          accessToken: resolveFigmaToken(config),
          fileKey:     parsed.fileKey,
          nodeId:      parsed.nodeId,
          noCache:     args.noCache,
        });
        const root            = findComponentRoot(rawNode);
        const rootRecord      = root as unknown as Record<string, unknown>;
        const textStyles      = extractTextStyles(rootRecord, config.typography.scale);
        const spacingEntries  = extractSpacingEntries(rootRecord);
        const iconSizes       = extractIconSizes(rootRecord);
        const cornerRadii     = extractCornerRadii(rootRecord);

        const liveSpec: FixelSpec = {
          figmaFile:    parsed.fileKey,
          figmaNode:    parsed.nodeId,
          generatedAt:  new Date().toISOString(),
          resolvedTextStyles: textStyles.map((s) => ({
            fontSize: s.fontSize, fontWeight: s.fontWeight,
            token: s.token, lineHeight: s.lineHeight,
          })),
          resolvedSpacing:     [...spacingEntries.values()],
          resolvedIconSizes:   [...iconSizes.values()],
          resolvedCornerRadii: [...cornerRadii].sort((a, b) => a - b),
        };
        return { entry, liveSpec };
      }),
    );

    for (let i = 0; i < fetches.length; i++) {
      const result = fetches[i];
      const entry  = entries[i];
      if (result.status === 'rejected') {
        console.error(`  ${C.red}✗${C.reset}  ${entry.name}: Figma fetch failed — ${result.reason}`);
        reports.push({
          name:        entry.name,
          specPath:    null,
          codePath:    entry.codePath,
          figmaNode:   parsed.nodeId,
          generatedAt: '',
          checks:      [{ label: 'Figma fetch', figmaValue: '', status: 'fail', detail: String(result.reason) }],
          status:      'fail',
        });
        continue;
      }
      const { liveSpec } = result.value;
      const code   = fs.readFileSync(entry.codePath, 'utf8');
      const checks = runDriftChecks(code, liveSpec, overrides, entry.name, config);

      reports.push({
        name:        entry.name,
        specPath:    entry.specPath,
        codePath:    entry.codePath,
        figmaNode:   liveSpec.figmaNode,
        generatedAt: new Date().toISOString(),
        checks,
        status:      componentStatus(checks),
      });
    }
  } else {
    // ── Offline mode: compare against stored spec ─────────────────────────────
    for (const entry of entries) {
      const spec   = JSON.parse(fs.readFileSync(entry.specPath!, 'utf8')) as FixelSpec;
      const code   = fs.readFileSync(entry.codePath, 'utf8');

      const specIsEmpty =
        (!spec.resolvedTextStyles  || spec.resolvedTextStyles.length  === 0) &&
        (!spec.resolvedSpacing     || spec.resolvedSpacing.length     === 0) &&
        (!spec.resolvedIconSizes   || spec.resolvedIconSizes.length   === 0) &&
        (!spec.resolvedCornerRadii || spec.resolvedCornerRadii.length === 0);

      if (specIsEmpty) {
        console.warn(
          `\n  ${C.yellow}⚠  WARN  ${entry.name}${C.reset}\n` +
          `   Spec has no checkable fields — typography, spacing, border-radius, and icon size checks were all skipped.\n` +
          `   Only raw hex was checked. Run fixel generate to populate the spec, or verify your typography scale and token file are configured correctly.\n`,
        );
        reports.push({
          name:        entry.name,
          specPath:    entry.specPath,
          codePath:    entry.codePath,
          figmaNode:   spec.figmaNode,
          generatedAt: spec.generatedAt,
          checks:      [{ label: 'Spec completeness', figmaValue: '', status: 'fail', detail: 'Spec has no checkable fields' }],
          status:      'fail',
        });
        continue;
      }

      const checks = runDriftChecks(code, spec, overrides, entry.name, config);

      reports.push({
        name:        entry.name,
        specPath:    entry.specPath,
        codePath:    entry.codePath,
        figmaNode:   spec.figmaNode,
        generatedAt: spec.generatedAt,
        checks,
        status:      componentStatus(checks),
      });
    }
  }

  // ── Per-component output ───────────────────────────────────────────────────
  for (const report of reports) {
    printComponentReport(report, isLive);
  }

  // ── Summary ────────────────────────────────────────────────────────────────
  const passed  = reports.filter((r) => r.status === 'pass').length;
  const warned  = reports.filter((r) => r.status === 'warn').length;
  const failed  = reports.filter((r) => r.status === 'fail').length;
  const totalW  = reports.flatMap((r) => r.checks).filter((c) => c.status === 'warn').length;
  const totalE  = reports.flatMap((r) => r.checks).filter((c) => c.status === 'fail').length;
  const totalOv = reports.flatMap((r) => r.checks).filter((c) => c.status === 'override').length;

  console.log(`\n  ${'─'.repeat(60)}`);
  console.log(`  ${C.bold}Summary${C.reset}  ${reports.length} component(s)\n`);
  if (passed > 0)  console.log(`    ${C.green}✓${C.reset}  ${passed} passed`);
  if (warned > 0)  console.log(`    ${C.yellow}⚠${C.reset}  ${warned} passed with warnings  (${totalW} total warnings)`);
  if (failed > 0)  console.log(`    ${C.red}✗${C.reset}  ${failed} failed  (${totalE} total errors)`);
  if (totalOv > 0) console.log(`    ${C.cyan}⊘${C.reset}  ${totalOv} check(s) overridden  (fixel.overrides.json)`);

  // ── --write-overrides interactive flow ────────────────────────────────────
  if (args.writeOverrides) {
    if (!process.stdout.isTTY) {
      console.warn(
        `\n  ${C.yellow}⚠${C.reset}  --write-overrides requires an interactive terminal.\n` +
        `     Skipping prompts. Run this command locally to register overrides.\n`,
      );
    } else {
      // Collect checks that are failing/warning AND have an overrideKey.
      // Audit-pattern checks (no overrideKey) are excluded — use // fixel-ignore for those.
      const overrideable = reports.flatMap((r) =>
        r.checks
          .filter((c) => (c.status === 'fail' || c.status === 'warn') && c.overrideKey)
          .map((c) => ({ report: r, check: c })),
      );

      if (overrideable.length === 0) {
        console.log(
          `\n  ${C.dim}  No overrideable drift found.  All spec checks already pass.${C.reset}\n`,
        );
      } else {
        console.log(
          `\n  ${C.bold}  Register intentional overrides${C.reset}` +
          `  ${C.dim}${overrideable.length} failing check(s)${C.reset}\n`,
        );

        // Dynamic import — avoid loading inquirer in non-interactive verify runs
        const { confirm, input } = await import('@inquirer/prompts');
        let changed = false;

        for (const { report, check } of overrideable) {
          const approve = await confirm({
            message: `  ${report.name} › ${check.label.trim()}  — mark as intentional override?`,
            default: false,
          });

          if (!approve) continue;

          const reason = await input({
            message: '  Reason (press Enter to use default):',
            default: 'Intentional deviation',
          });

          setOverride(overrides, report.name, check.overrideKey!, {
            figmaValue: check.figmaValue,
            codeValue:  check.detail.slice(0, 120),
            reason:     reason.trim() || 'Intentional deviation',
            date:       new Date().toISOString().slice(0, 10),
          });
          changed = true;
        }

        if (changed) {
          saveOverrides(process.cwd(), overrides);
          console.log(
            `\n  ${C.green}✓${C.reset}  Overrides saved to fixel.overrides.json\n` +
            `  ${C.dim}Re-run "fixel verify" — registered checks will now show ⊘.${C.reset}\n`,
          );
        } else {
          console.log(`\n  ${C.dim}  No overrides registered.${C.reset}\n`);
        }
      }
    }
  }

  // ── Exit ──────────────────────────────────────────────────────────────────
  if (failed > 0) {
    if (!args.writeOverrides) {
      // Only print the verbose guidance if --write-overrides wasn't already used
      // (the user already saw the prompt flow and chose not to override everything)
      console.log(
        `\n  ${C.red}Components above do not match their Figma specification.${C.reset}\n` +
        `  Fix the mismatches, run fixel generate --force to regenerate,\n` +
        `  or use --write-overrides to register intentional deviations.\n`,
      );
    }
    process.exit(1);
  } else if (warned > 0) {
    console.log(`\n  ${C.yellow}All components pass — review warnings before merging.${C.reset}\n`);
  } else {
    console.log(`\n  ${C.green}${C.bold}All components match their Figma specification.${C.reset}\n`);
  }
}

// ─── Entry ────────────────────────────────────────────────────────────────────

main().catch((err: unknown) => {
  if (err instanceof FixelConfigError) {
    console.error(`\n  ${C.yellow}Config error:${C.reset} ${err.message}\n`);
    process.exit(1);
  }
  if (err instanceof FigmaApiError) {
    console.error(`\n  ${C.red}Figma API error:${C.reset} ${err.message}\n`);
    if ((err as FigmaApiError).statusCode === 403) {
      console.error(`  Check that FIGMA_ACCESS_TOKEN is set and has read access to this file.\n`);
    }
    process.exit(1);
  }
  console.error(`\n  ${C.red}Error:${C.reset} ${err instanceof Error ? err.message : String(err)}\n`);
  process.exit(1);
});
